version: '3'

services:
  spectre-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "15432:5432"
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge